//the enumerations

export const Confidence = {

  HUMAN : "HUMAN",
  AI_REVIEWED : "AI_REVIEWED", // ai doc modified by a human 
  AI_ONLY: "AI_ONLY", //generated by the ai and untouched by a human
}as const;
export type Confidence = typeof Confidence[keyof typeof Confidence];


export const Severity = {

  CRITICAL: "CRITICAL",
  WARNING: "WARNING",
  INFO: "INFO",

}as const;
export type Severity = typeof Severity[keyof typeof Severity];


export const AlertStatus ={
  
  OPEN: "OPEN",
  REVIEWED: "REVIEWED",
  RESOLVED: "RESOLVED",
}as const

export type AlertStatus = typeof AlertStatus[keyof typeof AlertStatus];
